stateDiagram-v2
    [*] --> UserInput
    UserInput --> ChatAgent
    state ChatAgent {
        [*]  -->  Runner
        state RetrievalTools {
            state DocRetrievalTool
            state CodeRetrievalTool
            state ProjectRetrievalTool
            state IssueRetrievalTool
            [*] --> DocRetrievalTool
            [*] --> CodeRetrievalTool
            [*] --> ProjectRetrievalTool
            [*] --> IssueRetrievalTool
        }
        Runner --> RetrievalTools
        RetrievalTools --> Runner
    }

    state CoderAgent {
        [*] --> CodeRunner
        state CodeTools {
            state CodeSearchTool
            state CodeReviewTool
            state CodeBuildTool
            [*] --> CodeSearchTool
            [*] --> CodeReviewTool
            [*] --> CodeBuildTool
            CodeSearchTool --> [*]
            CodeReviewTool --> [*]
            CodeBuildTool --> [*]
        }
        CodeRunner --> CodeTools
        CodeTools --> CodeRunner
    }
    ChatAgent --> CoderAgent
    CoderAgent --> ChatAgent

    ChatAgent --> Output
    
    state TesterAgent {
        [*] --> TestRunner
        state TestTools {
            state TestCommandTool
            state TestReviewTool
            state IssueSearchTool
            [*] --> TestSearchTool
            [*] --> TestReviewTool
            [*] --> IssueSearchTool
            TestSearchTool --> [*]
            TestReviewTool --> [*]
            IssueSearchTool --> [*]
        }
        TestRunner --> TestTools
        TestTools --> TestRunner
    }

    ChatAgent --> TesterAgent
    TesterAgent --> ChatAgent

    Output --> [*]