stateDiagram-v2
    [*] --> UserInput
    UserInput --> ChatAgent
    
    state ChatAgent {
        [*]  -->  Runner
        state RetrievalTools {
            state DocRetrievalTool
            state CodeRetrievalTool
            state ProjectRetrievalTool
            state IssueRetrievalTool
            [*] --> DocRetrievalTool
            [*] --> CodeRetrievalTool
            [*] --> ProjectRetrievalTool
            [*] --> IssueRetrievalTool
        }
        Runner --> RetrievalTools
        RetrievalTools --> Runner
    }

    state CoderAgent {
        [*] --> CodeRunner
        CodeRunner --> SearchCodeExamples
        SearchCodeExamples --> ReadReferences
        ReadReferences --> BuildLoop
        state BuildLoop {
            state WriteCode
            state CodeBuildTool
            [*] --> WriteCode
            WriteCode --> CodeBuildTool
            CodeBuildTool --> QueryDocsIssues
            QueryDocsIssues --> WriteCode
            CodeBuildTool --> [*]
        }
    }
    ChatAgent --> CoderAgent
    CoderAgent --> Output
    ChatAgent --> Output
    

    Output --> [*]
